# NumPy Practice Project (Reworked Exercises)
Solve each task in the code cell below it.

In [102]:
# Import NumPy using the standard alias and create 1D, 2D and 3D arrays for practice.
import numpy as np

a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],
              [2,3,4]])
a3 = np.array([[[1,2,3],
                [3.4,3,6.7],
                [2,5,9]]])

a1
a2
a3

array([[[1. , 2. , 3. ],
        [3.4, 3. , 6.7],
        [2. , 5. , 9. ]]])

In [103]:
# Inspect your arrays by finding shape, dimensions, data type, size and Python object type.
a3.shape
a2.ndim
a1.dtype
a2.size

6

In [104]:
# Convert one NumPy array into a Pandas DataFrame and observe tabular representation.
import pandas as pd
array_dataframe = pd.DataFrame(a2)
array_dataframe

,0,1,2
0,1,2,3
1,2,3,4


In [105]:
# Create arrays filled with ones and zeros using specific shapes.
arr = np.zeros((2,3))
aar = np.ones((2,3))
arr,aar

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [106]:
# Generate arrays using arange with custom step values.
arrange_aarray = np.arange(1,30,2)
arrange_aarray

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [107]:
# Create random integer arrays and random float arrays with different shapes.
arra = np.random.randint(0,20,size=(3,5))
arra

array([[ 8,  1, 19, 14,  6],
       [11,  7, 14,  2, 13],
       [16,  3, 17,  7,  3]], dtype=int32)

In [108]:
# Set a random seed and regenerate arrays to observe reproducibility.
np.random.seed(42)

arr2 = np.random.randint(1,10,size=(2,3))
arr2

array([[7, 4, 8],
       [5, 7, 3]], dtype=int32)

In [109]:
# Create an array and practice finding unique values.
np.random.seed(42)

prac_array = np.random.randint(1,10,size=15)

print(prac_array)

np.unique(prac_array) 

[7 4 8 5 7 3 7 8 5 4 8 8 3 6 5]


array([3, 4, 5, 6, 7, 8], dtype=int32)

In [110]:
# Use indexing to access rows, columns and slices from arrays.
a3[:2:3]

array([[[1. , 2. , 3. ],
        [3.4, 3. , 6.7],
        [2. , 5. , 9. ]]])

In [111]:
# Practice array arithmetic using addition, subtraction, multiplication and division.
array_maths = a1 + a2
array_maths= a2- a1
array_maths

array([[0, 0, 0],
       [1, 1, 1]])

In [112]:
# Compare arrays using greater than, less than and equality operations.
a1 >= a2
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [113]:
# Use aggregation functions such as sum, mean, min, max and standard deviation.
np.sum([a1])
np.mean([a2])
np.max([a3])
np.mod([a1],2)
np.std([a1])

np.float64(0.816496580927726)

In [114]:
# Reshape arrays into different dimensions and verify shapes.
arr2.reshape(2,3,1)
arra.reshape(3,5)

array([[ 8,  1, 19, 14,  6],
       [11,  7, 14,  2, 13],
       [16,  3, 17,  7,  3]], dtype=int32)

In [115]:
# Transpose a multidimensional array and study what changes.
a3.T

array([[[1. ],
        [3.4],
        [2. ]],

       [[2. ],
        [3. ],
        [5. ]],

       [[3. ],
        [6.7],
        [9. ]]])

In [116]:
# Create two arrays and perform dot product operations.
array_1 = np.random.randint(1,9,size=(3,4))
array_2 = np.random.randint(1,9,size=(4,3))
np.dot(array_1,array_2)


array([[ 80,  70,  64],
       [ 94, 104,  62],
       [ 59,  62,  39]], dtype=int32)

In [117]:
# Sort arrays and experiment with argsort.
np.sort(array_1)
np.argsort(array_2)

array([[2, 1, 0],
       [0, 1, 2],
       [2, 0, 1],
       [1, 2, 0]])

In [118]:
# Use boolean masking to filter values meeting conditions.
array_1[array_1>2]

array([8, 4, 6, 6, 8, 4, 5, 4], dtype=int32)

In [119]:
# Generate sample image-like arrays and practice basic slicing.
img = np.random.randint(0,256,size=(5,5))
img

array([[207,  14, 189, 189, 174],
       [189,  50, 107,  54, 243],
       [ 63, 248, 130, 228,  50],
       [134,  20,  72, 166,  17],
       [131,  88,  59,  13, 241]], dtype=int32)

In [120]:
# Explore broadcasting with arrays of different shapes.
c = a1 + a3
c

array([[[ 2. ,  4. ,  6. ],
        [ 4.4,  5. ,  9.7],
        [ 3. ,  7. , 12. ]]])

In [121]:
# Create mini exercises involving practical data calculations using NumPy.
prices = np.array([200,350,500,150])

# Average price
prices.mean()

# Total sales
prices.sum()

# Highest price
prices.max()

# Lowest price
prices.min()

np.int64(150)

# Write a short reflection on what you observed about indexing, broadcasting and vectorized operations.
# I observed that indexing helps access specific elements and portions of arrays easily. 
# Broadcasting allows operations between arrays of different shapes without extra loops. 
# Vectorized operations make calculations faster and simpler compared to writing manual loops.