# NumPy Practice Project (Reworked Exercises)
Solve each task in the code cell below it.

In [12]:
# Import NumPy using the standard alias and create 1D, 2D and 3D arrays for practice.
import numpy as np

a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],
              [2,3,4]])
a3 = np.array([[[1,2,3],
                [3.4,3,6.7],
                [2,5,9]]])

a1
a2
a3

array([[[1. , 2. , 3. ],
        [3.4, 3. , 6.7],
        [2. , 5. , 9. ]]])

In [13]:
# Inspect your arrays by finding shape, dimensions, data type, size and Python object type.
a3.shape
a2.ndim
a1.dtype
a2.size

6

In [14]:
# Convert one NumPy array into a Pandas DataFrame and observe tabular representation.
import pandas as pd
array_dataframe = pd.DataFrame(a2)
array_dataframe

,0,1,2
0,1,2,3
1,2,3,4


In [15]:
# Create arrays filled with ones and zeros using specific shapes.
arr = np.zeros((2,3))
aar = np.ones((2,3))
arr,aar

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [16]:
# Generate arrays using arange with custom step values.
arrange_aarray = np.arange(1,30,2)
arrange_aarray

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [17]:
# Create random integer arrays and random float arrays with different shapes.
arra = np.random.randint(0,20,size=(3,5))
arra

array([[ 1, 11,  5,  1,  0],
       [11, 11, 16,  9, 15],
       [14, 14, 18, 11, 19]], dtype=int32)

In [18]:
# Set a random seed and regenerate arrays to observe reproducibility.
np.random.seed(42)

arr2 = np.random.randint(1,10,size=(2,3))
arr2

array([[7, 4, 8],
       [5, 7, 3]], dtype=int32)

In [19]:
# Create an array and practice finding unique values.
np.random.seed(42)

prac_array = np.random.randint(1,10,size=15)

print(prac_array)

np.unique(prac_array) 

[7 4 8 5 7 3 7 8 5 4 8 8 3 6 5]


array([3, 4, 5, 6, 7, 8], dtype=int32)

In [22]:
# Use indexing to access rows, columns and slices from arrays.
a3[:2:3]

array([[[1. , 2. , 3. ],
        [3.4, 3. , 6.7],
        [2. , 5. , 9. ]]])

In [25]:
# Practice array arithmetic using addition, subtraction, multiplication and division.
array_maths = a1 + a2
array_maths= a2- a1
array_maths

array([[0, 0, 0],
       [1, 1, 1]])

In [28]:
# Compare arrays using greater than, less than and equality operations.
a1 >= a2
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
# Use aggregation functions such as sum, mean, min, max and standard deviation.


In [ ]:
# Reshape arrays into different dimensions and verify shapes.


In [ ]:
# Transpose a multidimensional array and study what changes.


In [ ]:
# Create two arrays and perform dot product operations.


In [ ]:
# Sort arrays and experiment with argsort.


In [ ]:
# Use boolean masking to filter values meeting conditions.


In [ ]:
# Generate sample image-like arrays and practice basic slicing.


In [ ]:
# Explore broadcasting with arrays of different shapes.


In [ ]:
# Create mini exercises involving practical data calculations using NumPy.


In [ ]:
# Write a short reflection on what you observed about indexing, broadcasting and vectorized operations.
